package nl.hackyourfuture.project.backend.auth.dto;

import io.swagger.v3.oas.annotations.media.Schema;
import nl.hackyourfuture.project.backend.user.Role;
import nl.hackyourfuture.project.backend.user.User;

import java.time.OffsetDateTime;
import java.util.UUID;

@Schema(description = "User information returned after registration or login")
public record AuthResponse(
    @Schema(
        description = "Unique identifier of the user, generated by the server",
        example = "effe1126-329f-4f31-942c-31bc0be4d672",
        requiredMode = Schema.RequiredMode.REQUIRED
    )
    UUID userId,

    @Schema(
        description = "User role, either 'user' or 'admin'. Defaults to 'user'",
        example = "user",
        requiredMode = Schema.RequiredMode.REQUIRED
    )
    Role role,

    @Schema(
        description = "Name of the user",
        example = "Anouk de Vries",
        requiredMode = Schema.RequiredMode.REQUIRED
    )
    String name,

    @Schema(
        description = "Email address of the user",
        example = "anouk.devries@example.com",
        requiredMode = Schema.RequiredMode.REQUIRED
    )
    String email,

    @Schema(
        description = "Timestamp when the user account was created",
        example = "2026-08-15T09:30:00Z",
        requiredMode = Schema.RequiredMode.REQUIRED
    )
    OffsetDateTime createdAt) {
  public static AuthResponse from(User user) {
    return new AuthResponse(
        user.getId(),
        user.getRole(),
        user.getName(),
        user.getEmail(),
        user.getCreatedAt()
    );
  }
}
