package nl.hackyourfuture.project.backend.event.dto;

import io.swagger.v3.oas.annotations.media.Schema;

import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.UUID;

import nl.hackyourfuture.project.backend.event.model.Event;

@Schema(description = "An event as returned by the API")
public record EventResponse(


        @Schema(
                description = "Unique identifier of the event, generated by the server",
                example = "b6db1c3d-e075-44f4-9158-7c02704aeec8",
                requiredMode = Schema.RequiredMode.REQUIRED
        )
        UUID id,

        @Schema(
                description = "Title of the event",
                example = "Amsterdam Dance Event: Club Night",
                requiredMode = Schema.RequiredMode.REQUIRED
        )
        String title,

        @Schema(
                description = "Detailed description of the event",
                example = "An official Amsterdam Dance Event club night"
        )
        String description,

        @Schema(
                description = "Unique identifier of the event category",
                example = "cf3d47d1-0a47-42bb-b516-b6fc72014abb",
                requiredMode = Schema.RequiredMode.REQUIRED
        )
        UUID categoryId,

        @Schema(
                description = "Unique identifier of the event address",
                example = "5bf0aee7-ad74-49b7-8248-63c0d648b130",
                requiredMode = Schema.RequiredMode.REQUIRED
        )
        UUID addressId,

        @Schema(
                description = "Date and time when the event starts",
                example = "2026-09-12T21:00:00+02:00",
                requiredMode = Schema.RequiredMode.REQUIRED
        )
        OffsetDateTime startAt,

        @Schema(
                description = "Date and time when the event ends",
                example = "2026-09-13T04:00:00+02:00",
                requiredMode = Schema.RequiredMode.REQUIRED
        )
        OffsetDateTime endAt,

        @Schema(
                description = "Event price in euros",
                example = "24.00",
                requiredMode = Schema.RequiredMode.REQUIRED
        )
        BigDecimal price,

        @Schema(
                description = "Unique identifier of the admin who created the event",
                example = "effe1126-329f-4f31-942c-31bc0be4d672",
                requiredMode = Schema.RequiredMode.REQUIRED
        )
        UUID createdByUserId,

        @Schema(
                description = "Whether the event has been cancelled by admin",
                example = "false",
                requiredMode = Schema.RequiredMode.REQUIRED
        )
        boolean cancelled

) {

    public static EventResponse from(Event event) {
        return new EventResponse(
                event.id(),
                event.title(),
                event.description(),
                event.categoryId(),
                event.addressId(),
                event.startAt(),
                event.endAt(),
                event.price(),
                event.createdByUserId(),
                event.cancelled()
        );
    }
}